openapi: 3.0.3
info:
  title: Swagger Task Killer - OpenAPI 3.0
  description: |-
    Este é um servidor para o Task Killer baseado na especificação OpenAPI 3.0.

    _As rotas são baseadas em 3 models: listas, tarefas e o controle de usuarios._
    
    Links:
    - [GitHub - Task Killer](https://github.com/vghessel/taskKiller)
    - [Arquivo swagger.yaml no repositório](https://github.com/vghessel/taskKiller/blob/main/backend/swagger.yml)
  contact:
    email: vgerlachhessel@gmail.com
  version: 1.0.11
servers:
  - url: http://localhost:5000
tags:
  - name: tarefas
    description: Tudo sobre as tarefas
  - name: listas
    description: Tudo sobre as listas de tarefas
  - name: usuários
    description: Operações de login e signup
paths:
  /api/tasks:
    get:
      tags:
        - tarefas
      summary: Obter todas as tarefas
      description: Obtenha todas as tarefas sem filtro por ID
      parameters:
        - name: JWT
          in: header
          description: 'Json Web Token'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Operação efetuada com sucesso!
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: integer
                  format: int32
    post:
      tags:
        - tarefas
      summary: Criar tarefa
      description: Crie uma tarefa enviando as informações necessárias
      parameters:
        - name: JWT
          in: header
          description: 'Json Web Token'
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TarefaPost'
      responses:
        '200':
          description: Operação realizada com sucesso!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TarefaPost'
        '400':
          description: Invalid input
  /api/tasks/{taskId}:
    get:
      tags:
        - tarefas
      summary: Obter uma tarefa pelo ID
      description: Obtenha uma tarefa enviando o ID através da URL
      parameters:
        - name: taskId
          in: path
          description: ID da tarefa que deseja buscar
          required: true
          schema:
            type: integer
            format: int64
        - name: JWT
          in: header
          description: 'Json Web Token'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Operação efetuada com sucesso!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TarefaPost'          
        '400':
          description: ID inválido
        '404':
          description: Tarefa não encontrada
    put:
      tags:
        - tarefas
      summary: Atualizar uma tarefa existente pelo ID
      description: Atualize uma tarefa existente alterando os campos desejados
      parameters:
        - name: taskId
          in: path
          description: ID da tarefa que deseja atualizar
          required: true
          schema:
            type: integer
            format: int64
        - name: JWT
          in: header
          description: 'Json Web Token'
          required: true
          schema:
            type: string
      requestBody:
        description: Atualize uma tarefa já existente dentro de uma lista
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TarefaPut'
      responses:
        '200':
          description: Operação efetuada com sucesso!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TarefaPut'          
        '400':
          description: ID inválido
        '404':
          description: Tarefa não encontrada
    delete:
      tags:
        - tarefas
      summary: Excluir uma tarefa pelo ID
      description: Exclue uma tarefa enviando o ID através da URL
      parameters:
        - name: taskId
          in: path
          description: ID da tarefa que deseja deletar
          required: true
          schema:
            type: integer
            format: int64
        - name: JWT
          in: header
          description: 'Json Web Token'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Tarefa excluída com sucesso!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TarefaPost'          
        '400':
          description: ID inválido
        '404':
          description: Tarefa não encontrada
  /api/lists:
    get:
      tags:
        - listas
      summary: Obter todas as listas de tarefas
      description: Obtenha todas as listas sem filtro por I
      parameters:
        - name: JWT
          in: header
          description: 'Json Web Token'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Operação efetuada com sucesso!
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: integer
                  format: int32
    post:
      tags:
        - listas
      summary: Criar lista
      description: Crie uma lista enviando as informações necessárias
      parameters:
        - name: JWT
          in: header
          description: 'Json Web Token'
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListaPostPut'
      responses:
        '200':
          description: Operação realizada com sucesso!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListaPostPut'
        '400':
          description: Invalid input
  /api/lists/{listId}:
    get:
      tags:
        - listas
      summary: Obter uma lista pelo ID
      description: Obtenha uma lista enviando o ID através da URL
      parameters:
        - name: listId
          in: path
          description: ID da lista que deseja buscar
          required: true
          schema:
            type: integer
            format: int64
        - name: JWT
          in: header
          description: 'Json Web Token'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Operação efetuada com sucesso!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TarefaPost'          
        '400':
          description: ID inválido
        '404':
          description: Lista não encontrada
    put:
      tags:
        - listas
      summary: Atualizar uma lista existente pelo ID
      description: Atualize uma lista existente alterando os campos desejados
      parameters:
        - name: listId
          in: path
          description: ID da lista que deseja atualizar
          required: true
          schema:
            type: integer
            format: int64
        - name: JWT
          in: header
          description: 'Json Web Token'
          required: true
          schema:
            type: string
      requestBody:
        description: Atualize uma lista já existente
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListaPostPut'
      responses:
        '200':
          description: Operação efetuada com sucesso!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListaPostPut'          
        '400':
          description: ID inválido
        '404':
          description: Lista não encontrada
    delete:
      tags:
        - listas
      summary: Excluir uma lista pelo ID
      description: Exclue uma lista enviando o ID através da URL
      parameters:
        - name: listId
          in: path
          description: ID da lista que deseja deletar
          required: true
          schema:
            type: integer
            format: int64
        - name: JWT
          in: header
          description: 'Json Web Token'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Lista excluída com sucesso!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TarefaPost'          
        '400':
          description: ID inválido
        '404':
          description: Lista não encontrada
  /api/signup:
    post:
      tags:
        - usuários
      summary: Criar um usuário
      description: Crie um novo usuário
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsuarioLoginSignup'
      responses:
        '200':
          description: Usuário cadastrado com sucesso!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsuarioLoginSignup'
        '400':
          description: Invalid input
  /api/login:
    post:
      tags:
        - usuários
      summary: Fça login com um usuário
      description: Faça login com um usuário
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsuarioLoginSignup'
      responses:
        '200':
          description: Login bem-sucedido!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsuarioLoginSignup'
        '401':
          description: Credenciais inválidas
        '400':
          description: Invalid input
components:
  schemas:
    TarefaPost:
      type: object
      properties:
        title:
          type: string
          example: Criar um novo projeto
        description:
          type: string
          example: Criar um projeto para divulgar nas redes sociais
        status:
          type: boolean
          example: false
        list:
          type: object
          properties:
            name:
              type: string
              example: Planos 2024
    TarefaPut:
      type: object
      properties:
        title:
          type: string
          example: Criar um novo projeto
        description:
          type: string
          example: Criar um projeto para divulgar nas redes sociais
        status:
          type: boolean
          example: false
      
    ListaPostPut:
      type: object
      properties:
        name:
          type: string
          example: Planos 2024
    UsuarioLoginSignup:
      type: object
      properties:
        username:
          type: string
          example: vhessel
        password:
          type: string
          example: 1234
